const { Sequelize, DataTypes } = require('sequelize');
const { sequelize } = require('../sequilize/sequilize');

const PobladoDTO=sequelize.define('poblado',{
    ubigeo:{
        type:DataTypes.STRING,
    },
    ccpp:{
        type:DataTypes.STRING
    },
    centro_poblado:{
        type:DataTypes.STRING,
    },
    categoria:{
        type:DataTypes.STRING
    },
    ubigeo_ccpp:{
        type:DataTypes.STRING,
    },
    longitud:{
        type:DataTypes.STRING
    },
    latitud:{
        type:DataTypes.STRING,
    },
    poblacion:{
        type:DataTypes.STRING
    },
    vivienda:{
        type:DataTypes.STRING,
    },
    agua:{
        type:DataTypes.STRING
    },
    electricidad:{
        type:DataTypes.STRING,
    },
    desague:{
        type:DataTypes.STRING
    },
    via_mayor_uso:{
        type:DataTypes.STRING,
    },
    transporte_mayor_uso:{
        type:DataTypes.STRING
    },
    frecuencia	:{
        type:DataTypes.STRING,
    },
    tiempo_capital:{
        type:DataTypes.STRING
    },
    distancia_capital:{
        type:DataTypes.STRING,
    },
    distancia_centro_poblado_educativo:{
        type:DataTypes.STRING
    },
    distancia_centro_salud_cerca:{
        type:DataTypes.STRING,
    },
    alumbrado_publico:{
        type:DataTypes.STRING
    },
    telefono_publico:{
        type:DataTypes.STRING,
    },
    local_comunal:{
        type:DataTypes.STRING
    },
    hostal:{
        type:DataTypes.STRING,
    },
    estacion_radio:{
        type:DataTypes.STRING
    },
    iiee_primaria:{
        type:DataTypes.STRING,
    },
    iiee_secundaria:{
        type:DataTypes.STRING
    },
    puesto_salud:{
        type:DataTypes.STRING,
    },
    puesto_policial:{
        type:DataTypes.STRING
    },
    oficina_correo:{
        type:DataTypes.STRING,
    },
    cabina_internet:{
        type:DataTypes.STRING
    },
    heladas_nevadas:{
        type:DataTypes.STRING,
    },
    granizadas:{
        type:DataTypes.STRING
    },
    lluvias:{
        type:DataTypes.STRING,
    },
    sequias:{
        type:DataTypes.STRING
    },
    vendavales:{
        type:DataTypes.STRING,
    },
    inundaciones:{
        type:DataTypes.STRING
    },
    derrumbes:{
        type:DataTypes.STRING,
    },
    huaycos:{
        type:DataTypes.STRING
    },
    desertificaciones:{
        type:DataTypes.STRING,
    },
    salinizaciones:{
        type:DataTypes.STRING
    },
    volcan:{
        type:DataTypes.STRING,
    },
    sismo:{
        type:DataTypes.STRING
    },
    tsunami:{
        type:DataTypes.STRING,
    },
    fenomeno_nat:{
        type:DataTypes.STRING
    },
    derrame_sustancias:{
        type:DataTypes.STRING,
    },
    gases_toxicos:{
        type:DataTypes.STRING
    },
    explosiones:{
        type:DataTypes.STRING,
    },
    incendios:{
        type:DataTypes.STRING
    },
    crianza_animales:{
        type:DataTypes.STRING,
    },
    zona_industrial:{
        type:DataTypes.STRING
    },
    zonas_aeroportuarias:{
        type:DataTypes.STRING,
    },
    relleno_sanitario:{
        type:DataTypes.STRING
    },
    subversiones:{
        type:DataTypes.STRING,
    },
    otro_peligro:{
        type:DataTypes.STRING
    },
    rio_quebrada:{
        type:DataTypes.STRING,
    },
    cuartel_militar:{
        type:DataTypes.STRING
    },
    via_ferrea:{
        type:DataTypes.STRING,
    },
    erosion:{
        type:DataTypes.STRING
    },
    precipicios:{
        type:DataTypes.STRING,
    },
    otros:{
        type:DataTypes.STRING
    },
    pistas_veredas:{
        type:DataTypes.STRING,
    },
    canales_drenaje:{
        type:DataTypes.STRING
    },
    idioma_lengua:{
        type:DataTypes.STRING,
    },
    altitud:{
        type:DataTypes.STRING
    },
    url:{
        type:DataTypes.STRING,
    }
}, {
    tableName: 'centros_poblados_detalles',
    timestamps: false,
  })

module.exports=PobladoDTO